# Generated by Django 6.1.1 on 2026-09-22 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('sales', 'Sales Summary Report'), ('customer', 'Customer RFM Analysis Report'), ('product', 'Product Performance Report'), ('prediction', 'Repurchase Prediction Report'), ('forecast', 'Sales Forecast Report')], max_length=50)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel (XLSX)'), ('html', 'Interactive HTML')], default='csv', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('row_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
