# Generated by Django 6.1.1 on 2026-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(db_index=True, default='IN', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('recency_days', models.IntegerField(default=0, help_text='Days since last order')),
                ('frequency_orders', models.IntegerField(default=0, help_text='Total lifetime orders')),
                ('monetary_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total lifetime spend', max_digits=14)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rfm_score', models.CharField(blank=True, max_length=10)),
                ('segment', models.CharField(choices=[('Champions', 'Champions'), ('Loyal Customers', 'Loyal Customers'), ('Potential Loyalists', 'Potential Loyalists'), ('Recent Customers', 'Recent Customers'), ('At Risk', 'At Risk'), ('Lost', 'Lost'), ('New Customer', 'New Customer')], db_index=True, default='New Customer', max_length=50)),
                ('first_order_date', models.DateField(blank=True, null=True)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-monetary_total'],
                'indexes': [models.Index(fields=['customer_id'], name='customers_c_custome_ec5e63_idx'), models.Index(fields=['segment'], name='customers_c_segment_78093c_idx'), models.Index(fields=['country'], name='customers_c_country_fc020b_idx')],
            },
        ),
    ]
