# Generated by Django 6.1.1 on 2026-09-22 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForecastRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(db_index=True)),
                ('horizon_days', models.IntegerField(default=30)),
                ('predicted_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('predicted_orders', models.IntegerField(default=0)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='predictions.mlmodelrecord')),
            ],
            options={
                'ordering': ['forecast_date'],
                'indexes': [models.Index(fields=['forecast_date'], name='forecasting_forecas_c00289_idx'), models.Index(fields=['horizon_days'], name='forecasting_horizon_008acf_idx')],
            },
        ),
    ]
